### ISSUE TITLE
邀请码申请的邮件模板链接有锅

### ISSUE THREAD

**Issue by abc1763613206** [MoeNetwork/MoeCraft#10]
### 问题描述
```
<p>请 <a href="accounts.moecraft.net/index.php?m=Home&c=User&a=reg" target="_blank">点击此处继续注册</a></p>
<p>若注册链接无法点击，您可以手动打开 <a href="accounts.moecraft.net" target="_blank">accounts.moecraft.net</a> 然后点击“注册”按钮</p>
```

`a`标签中的URL链接没有加协议头，导致有些浏览器会判定为相对链接形式。           
如在163邮箱读信页面，`accounts.moecraft.net/index.php?m=Home&c=User&a=reg`会被转换为`https://mail.163.com/js6/read/accounts.moecraft.net/index.php?m=Home&c=User&a=reg`，从而导致出错。          

### 解决方式

修改链接模板。         

`accounts.moecraft.net/index.php?m=Home&c=User&a=reg` -> `//accounts.moecraft.net/index.php?m=Home&c=User&a=reg`                 

（反正也没备案，干脆直接上HTTPS `accounts.moecraft.net/index.php?m=Home&c=User&a=reg` -> `https://accounts.moecraft.net/index.php?m=Home&c=User&a=reg`好了）

**Comment by abc1763613206** [comment]
`有关` -> `有锅`

**Comment by kenvix** [comment]
fixed
