### ISSUE TITLE
MoeCraft用户中心网页中“实时服务器状态”菜单选项不工作

### ISSUE THREAD

**Issue by Bryan351018** [MoeNetwork/MoeCraft#12]
# MoeCraft用户中心网页中的[“实时服务器状态”菜单选项](https://user.moecraft.net:8443/Doc/Public/status)的数据拉取没有响应。

我已尝试使用多个浏览器浏览网页，经测试，会很长时间地显示“正在拉取信息”，之后这段信息消失，而什么也不显示。“刷新数据”按钮也没有响应。
测试的浏览器：

- Google Chrome 80.0.3987.163
- Firefox 75.0
- Safari 13.0.5 (14608.5.12)

系统：macOS Mojave (10.14.6)，64位

**Comment by kenvix** [comment]
已修复这个问题。但目前MoeCraft具有多个子服务器，而用户中心当前只支持显示其中一个。目前选择了纯净服作为展示

**Comment by Bryan351018** [comment]
经过测试，该问题已被修复。
