### ISSUE TITLE
rftools护盾导致主进程阻塞

### ISSUE THREAD

**Issue by FlandreCirno** [MoeNetwork/MoeCraft#2]
rftools护盾投射器使用空间仓卡投射大规模护盾时会导致服务器主进程阻塞，进而全服掉线

**Comment by kenvix** [comment]
目前已经大幅削弱了RF护盾以缓解此问题

**Comment by FlandreCirno** [comment]
暂行解决方案：将rftools护盾投射器支持的护盾数量削减为1/16，未证实此种情况下空间仓卡投射2048大小的护盾是否会导致掉线

可替代解决方案：禁用空间仓卡护盾投射，采用护盾框架投射大规模护盾不会阻塞主进程

**Comment by FlandreCirno** [comment]
替代解决方案实现方式：
降低rftools护盾配置中的I:maxShieldDimension配置，可以限制护盾投射器空间仓卡投射的护盾大小，进而防止其投射过大的护盾

**Comment by kenvix** [comment]
好的，将在Update3采用此办法
