### ISSUE TITLE
机器无法破坏不透明方块

### ISSUE THREAD

**Issue by FlandreCirno** [MoeNetwork/MoeCraft#3]
在某次更新后，机器无法破坏不透明方块，在此之前也有方块破坏机制无法正常运作，因此此问题可能由复杂原因导致，需要进一步测试

**Comment by FlandreCirno** [comment]
确认直接受影响的有：
ExU2使用者：无法破坏不透明方块，其他功能不受影响
ExU2量子采石场：完全无法运行，无产出
可能相关的有：
OpenBlocks方块采掘器：无效
AE2破坏面板：无效

**Comment by FlandreCirno** [comment]
测试中仅AE2与Sponge共存时，AE2破坏面板在无参数下可正常工作，加入MoeCraft启动脚本中的参数后无法工作，怀疑Sponge的配置与此问题直接相关

**Comment by kenvix** [comment]
* 短期内不太可能删除sponge
* 能否确认问题3是哪个启动参数导致的
