### ISSUE TITLE
MoeCraft 5 待选模组

### ISSUE THREAD

**Issue by yoonhakcher** [MoeNetwork/MoeCraft#7]

**Comment by yoonhakcher** [comment]
- Just Enough Items (JEI)
- JourneyMap
- Inventory Tweaks
- ConnectedTexturesMod
- Mouse Tweaks
- FTB Utilities
- Controlling
- Wawla - What Are We Looking At
- Hwyla
- FoamFix for Minecraft
- Just Enough Resources (JER)
- Clumps
- NotEnoughItems
- Waila Harvestability
- JEI Bees
- JEI Integration
- Fullscreen Windowed (Borderless) for Minecraft
- Smooth Font
- Light Level Overlay Reloaded
- LagGoggles
---
- Tinkers Construct
- Chisel
- Iron Chests
- Storage Drawers
- ~~Extra Utilities~~
- Immersive Engineering
- BiblioCraft
- ~~Thermal Foundation~~
- ~~Thermal Expansion~~
- Botania
- Ender IO
- ~~RFTools~~
- ~~Actually Additions~~
- ~~Thermal Dynamics~~
- Tinkers' Tool Leveling
- Forestry
- Natura
- ~~Refined Storage~~
- OpenBlocks
- Quark
- ~~Industrial Foregoing~~
- Chest Transporter
- Bonsai Trees
- Morph-o-Tool
- PlusTiC
- ~~Integration Foregoing~~
- ~~Thermal Innovation~~
- Tech Reborn
- Woot
- Tinker I/O
- JAOPCA
- Roost
- ~~Thermal Cultivation~~

**Comment by w583695004** [comment]
注明下链接和说明?这样显得很乱

**Comment by w583695004** [comment]
- [Serene Seasons 静谧四季](https://minecraft.curseforge.com/projects/serene-seasons/images)
增加四季变化
- [Traverse遍历](https://minecraft.curseforge.com/projects/traverse/images)
轻量地形mod相比BOP要简洁些
- [Rustic 乡村](https://minecraft.curseforge.com/projects/rustic/images)
集装饰酿酒炼药与一样的mod很有情趣
- [Spice of Life: Carrot Edition 生活调味料胡萝卜版](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition)
生活调味料增益版保持营养均衡就能获得各种正面BUFF
- [Culinary Construct 组合三明治](https://minecraft.curseforge.com/projects/culinary-construct?gameCategorySlug=mc-mods&projectID=296676)
可以将各种食材组合起来配合生活调味料简直是绝配
- [Useful Interior 实用内饰](https://minecraft.curseforge.com/projects/useful-interior)
漂亮又实用的装饰方块
- [Yoyos 悠悠球](https://minecraft.curseforge.com/projects/yoyos)
搭配匠魂材料能做出各种功能的悠悠球
- [Xnet](https://minecraft.curseforge.com/projects/xnet?gameCategorySlug=mc-mods&projectID=260912)
RFtools作者制作的一个管道mod优点在于优化做的很好据作者本人测试即使铺设1w2管道也不会造成丝毫卡顿,非常nb个人强烈推荐
- [Magneticraft 磁场科技](https://minecraft.curseforge.com/projects/magneticraft/images)
和IE一样崇尚多方块结构模型精美，可惜知名度太低

**Comment by reserveword** [comment]
- [SimpleLogic Wires](https://minecraft.curseforge.com/projects/simplelogic-wires)
- [SimpleLogic Gates](https://minecraft.curseforge.com/projects/simplelogic-gates)
（这两个mod能够帮助搭建红石电路，搭建线路更自由和添加不同种类的电子元件）

另外，支持Xnet和植物魔法
