### ISSUE TITLE
【MoeCraft Authlib-Injector API 说明】中【将此按钮拖动至启动器】功能在Firefox下不可用

### ISSUE THREAD

**Issue by yushijinhun** [MoeNetwork/MoeCraft#9]
这是 Firefox 由来已久的一个 bug，把 `button` 换成 `div` 就能解决了。

参见：
* https://bugzilla.mozilla.org/show_bug.cgi?id=568313
* https://stackoverflow.com/questions/47635797/draggable-button-in-firefox

**Comment by kenvix** [comment]
fixed
